### PR TITLE
Implement webhook signature validation

### PR DESCRIPTION
**Pull request by compujuckel**
First proposal for implementing signature validation as documented here: https://developer.atlassian.com/cloud/trello/guides/rest-api/webhooks/#webhook-signatures

To make this usable via the Automation Engine, the validation should probably be moved to ConvertJsonToWebhookNotification.
Also I wasn't sure where the best place to put the Trello secret would be.
Please let me know your thoughts and I will move things around accordingly.

also, thanks for this library :) so far, it has been very pleasant to work with.

### CODE REVIEW

**Comment by rwjdk** [comment]
Hi @compujuckel, Thank you for the PR, and Nice that you would like to contribute 😎

I've been meaning to include the signature validation but have not yet come around to it so it is a good addition 🙏

Regarding the Secret, I was thinking if it might be better to add it to the [TrelloClientOptions](https://github.com/rwjdk/TrelloDotNet/wiki/TrelloClient#trelloclientoptions) ... That way every time you have a trelloClient, you also have the secret at hand, and you can better use User-secrets if you dependency inject the TrelloClient

As for use in the automation engine that could also be a welcome addition... I could see the `ProcessingRequest` with the JSON getting the "signature" and "webhookUrl" as optional params, and as for reuse of the new ValidateSignature method that could perhaps be a new static helper-class (WebhookSignatureValidator.IsValid(string json, string signature, string webhookUrl))

So if you are up for these changes I would be most grateful for the addition 💪

**Comment by compujuckel** [comment]
Sure, sounds good!
One last question: What should happen in AutomationController.ProcessJsonFromWebhookAsync when the signature validation fails? throw an AutomationException?

**Comment by rwjdk** [comment]
It is a good question (and same question for the one you already implemented)... I'm leaning toward just a return like you have, as throwing exception will just spam an errorlog...

Only worry about the direct return, is if someone implement it wrong and do not understand why.

**Comment by compujuckel** [comment]
> Only worry about the direct return, is if someone implement it wrong and do not understand why.

Yes, that's also my main concern. As an alternative, what do you think about adding a new parameter (e.g. EnableWebhookSignatureValidation) to TrelloClientOptions instead of implicitly enabling it when the API secret is set?
That way, you couldn't "accidentally" enable this feature and then wonder why nothing is working.

**Comment by rwjdk** [comment]
Gut feeling is that it would not really help with that and would just annoy. To me the process of sending of signature and url to the processor is the "enabling" of the feature... (Btw., If one that but have not set the secret it would properly be smart to throw an exception in that case)

So: 
- no secret and no signature/url = No validation
- Secret and no signature/url = No validation
- No secret and signature/url = Exception
- Secret + signature/url (all set correctly) = success validation
- Secret + signature/url (wrong data) = validation with silent return

If this cause issues for people implementing we can implement a debug mode in options later

**Review by rwjdk — CHANGES_REQUESTED** [review]

**Comment by rwjdk** [comment]
@compujuckel Are you still up for completing this PR, or do you wish me to accept it as is and do the final tweaking?

**Comment by compujuckel** [comment]
I'll most likely have time to work on it again in a few days, so if you're fine with waiting until then I'll finish it

**Comment by rwjdk** [comment]
@compujuckel No worries; take your time. It was just if you did not feel like it, it would be a shame to abandon the good work so far 😊

**Review by rwjdk — APPROVED** [review]

**Comment by rwjdk** [comment]
Awesome :-) ... I will merge and add you to the credits in the changelog. I expect version 1.9.0 with this included out very soon (today or tomorrow)

Again, thank for contributing 💪

**Pull request merged**
