### PR TITLE
GetActionsOfBoard optional parameters

### PR DESCRIPTION
**Pull request by mashbrno**
Added some of the missing parameters for GetActionsOfBoard method

### CODE REVIEW

**Comment by rwjdk** [comment]
Hi @mashbrno, Awesome that you wish to contribute to TrelloDotNet 🙌

I've looked at the code and everything seems to work, but one thing I'm can't seem to find a way to test is the "reactions" = true setting... How is that one supposed to work (it does not seem to bring any reactions to comments to the Action JSON in any way)?

**Comment by rwjdk** [comment]
@mashbrno Any update on this question before PR approval? I can also accept the PR and remove that specific param before release if you do not know what it means either,but I guess you put it there for a reason???

**Comment by mashbrno** [comment]
Hi,
I can omit that. When I was adding parameters I need, I add this just because it is available on the API for someone else to use. In fact I have no idea what is the default value (true or false), API doc is silent about that.

**Review by rwjdk — APPROVED** [review]
Looks good 😎

**Comment by rwjdk** [comment]
Your change is now released in TrelloDotNet 1.10.4 Nuget Package: https://www.nuget.org/packages/TrelloDotNet

Again; thank you for the contribution 🙇‍♂️, and have a nice weekend 🙌

**Pull request merged**
